col = [{'type': 'choice', 'name': 'Sex', 'data': [0.0, 1.0]},
 {'type': 'choice',
  'name': 'Educational level',
  'data': [2.0, 3.0, 1.0, 0.0, 4.0]},
 {'type': 'choice', 'name': 'Smoking status', 'data': [0.0, 1.0]},
 {'type': 'choice', 'name': 'PCI', 'data': [0.0, 1.0]},
 {'type': 'choice',
  'name': 'Number of affected vessels',
  'data': [1.0, 0.0, 3.0, 2.0, 4.0]},
 {'type': 'choice', 'name': 'HF', 'data': [1.0, 0.0]},
 {'type': 'choice', 'name': 'COPD', 'data': [0.0, 1.0]},
 {'type': 'choice', 'name': 'Hepatic disease', 'data': [0.0, 2.0, 1.0, 3.0]},
 {'type': 'choice', 'name': 'Antiplatelet', 'data': [1.0, 2.0, 0.0]},
 {'type': 'choice', 'name': 'Lipid-lowering drug', 'data': [1.0, 0.0, 2.0]},
 {'type': 'choice', 'name': 'PPI', 'data': [0.0, 1.0]},
 {'type': 'number', 'name': 'LOS', 'dtype': 'int', 'step': 1},
 {'type': 'number', 'name': 'DBP', 'dtype': 'int', 'step': 1},
 {'type': 'number', 'name': 'LA', 'dtype': 'int', 'step': 1},
 {'type': 'number', 'name': 'RA', 'dtype': 'int', 'step': 1},
 {'type': 'number', 'name': 'NOM', 'dtype': 'int', 'step': 1},
 {'type': 'number', 'name': 'FT3', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'FT4', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'PTA', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'TT', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'Fibrinogen', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'LDLC', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'ApoB', 'dtype': 'float', 'step': 0.01},
 {'type': 'number',
  'name': 'Albumin/globulin',
  'dtype': 'float',
  'step': 0.01},
 {'type': 'number', 'name': 'AST', 'dtype': 'float', 'step': 0.01},
 {'type': 'number',
  'name': 'Indirect bilirubin',
  'dtype': 'float',
  'step': 0.01},
 {'type': 'number', 'name': 'Creatinine', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'Uric acid', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'LDH', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'CKMB', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'Glucose', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'Monocyte', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'Basophil', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'RBC', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'Hemoglobin', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'RDW-SD', 'dtype': 'float', 'step': 0.01},
 {'type': 'number', 'name': 'Serum sodium', 'dtype': 'float', 'step': 0.01}]